---
- name: Setup EC2 Ubuntu instance
  hosts: localhost
  gather_facts: False
      
  tasks:
  
    - name: Create an ec2 instance
      ec2:
          key_name: "{{ keypair }}"
          group: my-instance  # security group
          image: "{{ ami }}"
          wait: true
          region: "{{ region }}"
          count: 1  # default
          count_tag:
            Name: WH
          instance_tags:
            Name: WH
          vpc_subnet_id: subnet-9bc6cde0
          assign_public_ip: yes
      register: ec2
          