---
- name: Setup EC2 Ubuntu instance
  hosts: localhost
  gather_facts: False
  
  vars:
      region: us-west-2
      instance_type: m3.medium
      ami: ami-f4cc1de2   # Ubuntu 16.04
      keypair: my-instance  # pem file name
      
  tasks:
  
    - name: Create an ec2 instance
      ec2:
          key_name: "{{ keypair }}"
          group: my-instance  # security group
          image: "{{ ami }}"
          wait: true
          region: "{{ region }}"
          count: 1  # default
          count_tag:
            Name: WH
          instance_tags:
            Name: WH
          vpc_subnet_id: subnet-9bc6cde0
          assign_public_ip: yes
      register: ec2
          