---

- name: Install python setuptools & docker
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python-setuptools
    - docker
    
- name: Ensure docker-engine is installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "docker-engine"

- name: Start docker
  service:
    name: docker
    state: running
    
- name: Install pypi
  easy_install: name=pip
  
- name: Install docker-py to latest
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-py